name: movie_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  internet_connection_checker_plus: ^2.7.2
  flutter_bloc: ^9.1.1
  json_annotation: ^4.9.0
  lottie: ^3.2.0
  flutter_launcher_icons: ^0.14.4
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  fpdart: ^1.1.1
  flutter_svg: ^2.1.0
  retrofit: ^4.5.0
  logger: ^2.4.0
  carousel_slider: ^5.1.1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  path_provider: ^2.1.5
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  retrofit_generator: '>=8.0.0 <10.0.0'
  build_runner: ^2.3.3
  json_serializable: ^6.8.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/config/
    - assets/images/
    - assets/images/lottie/
    - assets/images/svg/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Black.ttf
        - asset: fonts/Poppins-BlackItalic.ttf
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-BoldItalic.ttf
        - asset: fonts/Poppins-ExtraBold.ttf
        - asset: fonts/Poppins-ExtraBoldItalic.ttf
        - asset: fonts/Poppins-ExtraLight.ttf
        - asset: fonts/Poppins-ExtraLightItalic.ttf
        - asset: fonts/Poppins-Italic.ttf
        - asset: fonts/Poppins-Light.ttf
        - asset: fonts/Poppins-LightItalic.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-MediumItalic.ttf
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-SemiBold.ttf
        - asset: fonts/Poppins-SemiBoldItalic.ttf
        - asset: fonts/Poppins-Thin.ttf
        - asset: fonts/Poppins-ThinItalic.ttf